hero_pool={
 --死骑
 'npc_dota_hero_abaddon',
 --大屁股
 'npc_dota_hero_abyssal_underlord',
 --炼金
 'npc_dota_hero_alchemist',
 --冰魂
 'npc_dota_hero_ancient_apparition',
 --敌法
 'npc_dota_hero_antimage',
 --电狗
 'npc_dota_hero_arc_warden',
 --斧王
 'npc_dota_hero_axe',
 --痛苦之源
 'npc_dota_hero_bane',
 --蝙蝠骑士
 'npc_dota_hero_batrider',
 --兽王
 'npc_dota_hero_beastmaster',
 --血魔
 'npc_dota_hero_bloodseeker',
 --赏金
 'npc_dota_hero_bounty_hunter',
 --酒仙
 'npc_dota_hero_brewmaster',
 --刚被
 'npc_dota_hero_bristleback',
 --孕母蜘蛛
 'npc_dota_hero_broodmother',
 --人马
 'npc_dota_hero_centaur',
 --混沌
 'npc_dota_hero_chaos_knight',
 --陈
 'npc_dota_hero_chen',
 --骨弓
 'npc_dota_hero_clinkz',
 --冰女
 'npc_dota_hero_crystal_maiden',
 --黑暗贤者
 'npc_dota_hero_dark_seer',
 --戴泽
 'npc_dota_hero_dazzle',
 --死亡先知
 'npc_dota_hero_death_prophet',
 --萨尔
 'npc_dota_hero_disruptor',
 --末日使者
 'npc_dota_hero_doom_bringer',
 --龙骑士
 'npc_dota_hero_dragon_knight',
 --黑暗游侠
 'npc_dota_hero_drow_ranger',
 --土猫
 'npc_dota_hero_earth_spirit',
 --牛头
 'npc_dota_hero_earthshaker',
 --大牛
 'npc_dota_hero_elder_titan',
 --火猫
 'npc_dota_hero_ember_spirit',
 --小鹿
 'npc_dota_hero_enchantress',
 --谜团
 'npc_dota_hero_enigma',
 --虚空
 'npc_dota_hero_faceless_void',
 --先知
 'npc_dota_hero_furion',
 --矮人直升机
 'npc_dota_hero_gyrocopter',
 --哈斯卡
 'npc_dota_hero_huskar',
 --卡尔
 'npc_dota_hero_invoker',
 --双头龙
 'npc_dota_hero_jakiro',
 --剑圣
 'npc_dota_hero_juggernaut',
 --光法
 'npc_dota_hero_keeper_of_the_light',
 --船长
 'npc_dota_hero_kunkka',
 --军团
 'npc_dota_hero_legion_commander',
 --老鹿
 'npc_dota_hero_leshrac',
 --巫妖
 'npc_dota_hero_lich',
 --小狗
 'npc_dota_hero_life_stealer',
 --火女
 'npc_dota_hero_lina',
 --莱恩
 'npc_dota_hero_lion',
 --德鲁伊
 'npc_dota_hero_lone_druid',
 --月骑
 'npc_dota_hero_luna',
 --狼人
 'npc_dota_hero_lycan',
 --猛犸
 'npc_dota_hero_magnataur',
 --美杜莎
 'npc_dota_hero_medusa',
 --米波
 'npc_dota_hero_meepo',
 --白虎
 'npc_dota_hero_mirana',
 --大圣
 'npc_dota_hero_monkey_king',
 --水人
 'npc_dota_hero_morphling',
 --小娜迦
 'npc_dota_hero_naga_siren',
 --死灵法师
 'npc_dota_hero_necrolyte',
 --影魔
 'npc_dota_hero_nevermore',
 --夜魔
 'npc_dota_hero_night_stalker',
 --小强
 'npc_dota_hero_nyx_assassin',
 --黑鸟
 'npc_dota_hero_obsidian_destroyer',
 --蓝胖
 'npc_dota_hero_ogre_magi',
 --全能骑士
 'npc_dota_hero_omniknight',
 --神域者
 'npc_dota_hero_oracle',
 --PA幻影刺客
 'npc_dota_hero_phantom_assassin',
 --猴子
 'npc_dota_hero_phantom_lancer',
 --凤凰
 'npc_dota_hero_phoenix',
 --帕克
 'npc_dota_hero_puck',
 --屠夫
 'npc_dota_hero_pudge',
 --骨法
 'npc_dota_hero_pugna',
 --女王
 'npc_dota_hero_queenofpain',
 --发条
 'npc_dota_hero_rattletrap',
 --电棍
 'npc_dota_hero_razor',
 --隐刺
 'npc_dota_hero_riki',
 --拉比克
 'npc_dota_hero_rubick',
 --沙王
 'npc_dota_hero_sand_king',
 --毒狗
 'npc_dota_hero_shadow_demon',
 --小Y
 'npc_dota_hero_shadow_shaman',
 --伐木机
 'npc_dota_hero_shredder',
 --沉默术士
 'npc_dota_hero_silencer',
 --骷髅王
 'npc_dota_hero_skeleton_king',
 --天怒法师
 'npc_dota_hero_skywrath_mage',
 --大鱼人
 'npc_dota_hero_slardar',
 --小鱼人
 'npc_dota_hero_slark',
 --火枪
 'npc_dota_hero_sniper',
 --幽鬼
 'npc_dota_hero_spectre',
 --白牛
 'npc_dota_hero_spirit_breaker',
 --蓝猫
 'npc_dota_hero_storm_spirit',
 --斯温sv
 'npc_dota_hero_sven',
 --炸弹人
 'npc_dota_hero_techies',
 --圣堂ta
 'npc_dota_hero_templar_assassin',
 --恐怖利刃tb
 'npc_dota_hero_terrorblade',
 --潮汐
 'npc_dota_hero_tidehunter',
 --地精修补匠tk
 'npc_dota_hero_tinker',
 --小小
 'npc_dota_hero_tiny',
 --大树
 'npc_dota_hero_treant',
 --巨魔
 'npc_dota_hero_troll_warlord',
 --巨牙海民
 'npc_dota_hero_tusk',
 --尸王
 'npc_dota_hero_undying',
 --拍拍熊
 'npc_dota_hero_ursa',
 --复仇之魂vs
 'npc_dota_hero_vengefulspirit',
 --剧毒术士
 'npc_dota_hero_venomancer',
 --毒龙
 'npc_dota_hero_viper',
 --维萨吉
 'npc_dota_hero_visage',
 --术士
 'npc_dota_hero_warlock',
 --蚂蚁
 'npc_dota_hero_weaver',
 --风行者
 'npc_dota_hero_windrunner',
 --冰龙
 'npc_dota_hero_winter_wyvern',
 --小精灵
 'npc_dota_hero_wisp',
 --巫医
 'npc_dota_hero_witch_doctor',
 --宙斯
 'npc_dota_hero_zuus',
 --獣
 'npc_dota_hero_primal_beast',
 --马尔斯
 'npc_dota_hero_mars',
 --马西
 'npc_dota_hero_marci',
 --老奶奶
 'npc_dota_hero_snapfire',
 --大锤
 'npc_dota_hero_dawnbreaker',
 --小松鼠
 'npc_dota_hero_hoodwink',
 --花仙子
 'npc_dota_hero_dark_willow',
 --紫猫
 'npc_dota_hero_void_spirit',
 --天涯墨客
 'npc_dota_hero_grimstroke',
 --滚滚
 'npc_dota_hero_pangolier',
 --奶绿
 'npc_dota_hero_muerta'
}